# Generated by Django 4.1.1 on 2022-09-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_isvendor_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='isVendor',
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
